
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 10
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.83e894ce-b03c-4e81-ba9d-f3c3ae9a7ed1.PendingTasksCaseBNeg
      debug: true