
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 45
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.7b914974-355c-4cf1-a9fa-ed94392a264b.PendingTasksMixed
      debug: true