
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 10
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.620b85f7-c926-4eff-ac80-de8e2fa45b40.PendingTasksCaseBNeg
      debug: true