
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 15
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.2c72a6b1-9d4e-43c5-bc59-7cac91d81fca.PendingTasksMixed
      debug: true