
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 10
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.5eee8e9e-4f7c-47a1-ada6-02c600352b4e.PendingTasksCaseB
      debug: true