
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 45
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.ebc9824a-4361-488a-bb94-3aad4cb9682e.PendingTasksCaseB
      debug: true