
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 10
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.0a55ab6c-2c51-4f64-a728-b637d27b9090.PendingTasksCaseB
      debug: true