
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 15
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.4a965a0b-f70e-411e-9a31-2ce5e964bbf7.PendingTasksMixed
      debug: true