
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual_approval
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 15
    with:
      instructions: Approve or reject this manual approval task.
      approvers:  AutoTest.fa20b34f-fbb0-4ecb-8719-a5c71345e24c.PendingTasksCaseB
      debug: true