apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:

  github:
    steps:
      - name: Checkout1
        uses: cloudbees-io/checkout@v1
        id: checkout1
        env:
          RUNNER_DEBUG: "1"
      - name: Commit1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 1:"
          echo Repository URL = ${{ steps.checkout1.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout1.outputs.commit }}
          echo Commit URL = ${{ steps.checkout1.outputs.commit-url }}
          echo Ref = ${{ steps.checkout1.outputs.ref }}
          if [ "${{ steps.checkout1.outputs.ref }}" = "refs/heads/main" ]; then echo "HEAD is same"; else echo "Main is not fetched correctly"; exit 0; fi
  github-anotherrepo:
    steps:
      - name: Checkout2
        uses: cloudbees-io/checkout@v1
        id: checkout2
        with:
          provider: github
          repository: test-cdro-qa/qa-momento-go-sample
          ref: v1.0.0
        env:
          RUNNER_DEBUG: "1"
      - name: Commit2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 2:"
          echo "Inputs:"
          echo "  provider: github"
          echo "  repository: test-cdro-qa/qa-momento-go-sample"
          echo "  ref v1.0.0"
          echo Repository URL = ${{ steps.checkout2.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout2.outputs.commit }}
          echo Commit URL = ${{ steps.checkout2.outputs.commit-url }}
          echo Ref = ${{ steps.checkout2.outputs.ref }}
          echo "Date: 2025-11-27T23:47:41.400Z"
          if [ "${{ steps.checkout2.outputs.ref }}" = "v1.0.0" ]; then echo "Ref variables match, continue..."; else echo "Ref references do not match, exiting."; exit 0; fi
  github-anotherrepo-ref:
    steps:
      - name: Checkout3
        uses: cloudbees-io/checkout@v1
        id: checkout3
        with:
          provider: github
          repository: test-cdro-qa/qa-python-hello-world
          ref: e62c0b1d042ae1e3a34c25e1551d7a2ca46edc80
        env:
          RUNNER_DEBUG: "1"
      - name: Commit3
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Commit 3:"
          echo "Inputs:"
          echo "  provider: github"
          echo "  repository: test-cdro-qa/qa-python-hello-world"
          echo "  ref e62c0b1d042ae1e3a34c25e1551d7a2ca46edc80"
          echo Repository URL = ${{ steps.checkout3.outputs.repository-url }}
          echo Commit ID = ${{ steps.checkout3.outputs.commit }}
          echo Commit URL = ${{ steps.checkout3.outputs.commit-url }}
          echo Ref = ${{ steps.checkout3.outputs.ref }}
          if [ "${{ steps.checkout3.outputs.commit }}" = "e62c0b1d042ae1e3a34c25e1551d7a2ca46edc80" ]; then echo "Commits are same"; else echo "Commit details dees not match, exiting."; exit 0; fi
  