apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: pending_tasks_probe
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 25
    with:
      instructions: "probe5"
      approvers: "AutoTest.261b2102-48c3-49e9-b9a0-18ddf18eb388.PT"
      debug: true