apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: pt_Bneg
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 25
    with:
      instructions: "Bneg"
      approvers: "AutoTest.fd317441-e2c7-4c12-9f96-a1060fc50567.PTTeamBneg"
      debug: true