apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: pt_Bteam
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 25
    with:
      instructions: "Bteam"
      approvers: "AutoTest.86a328e9-c091-437b-9044-0bc9ee0b3cc4.PTTeamB"
      debug: true