apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: pt_B
on:
  workflow_dispatch:
jobs:
  ask-now:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    timeout-minutes: 25
    with:
      instructions: "B"
      approvers: "All users for organization"
      debug: true