
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishEvidenceItem
on:
  workflow_dispatch:
jobs:
  publishEvidenceItemJob:
    timeout-minutes: 3
    steps:
    - name: Publish Workflow Evidence Item
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: 32eb4271-89ac-4305-b86f-0222e2b77afd