
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishEvidenceItem
on:
  workflow_dispatch:
jobs:
  publishEvidenceItemJob:
    timeout-minutes: 3
    steps:
    - name: Publish Workflow Evidence Item
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: c2988ea9-4af5-4876-b73a-1342c282838d