
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishEvidenceItem
on:
  workflow_dispatch:
jobs:
  publishEvidenceItemJob:
    timeout-minutes: 3
    steps:
    - name: Publish Workflow Evidence Item
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: 07dbe293-27b3-412e-b23f-cc92ba827d27