
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishEvidenceItem
on:
  workflow_dispatch:
jobs:
  publishEvidenceItemJob:
    timeout-minutes: 3
    steps:
    - name: Publish Workflow Evidence Item
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: 87890c28-9167-4bbd-aff4-94b0d983bc2b