
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: publishEvidenceItem
on:
  workflow_dispatch:
jobs:
  publishEvidenceItemJob:
    timeout-minutes: 3
    steps:
    - name: Publish Workflow Evidence Item
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: c0c5416b-7308-48f1-919e-720f58e8b9ff